service: skincare-resume-app
image: sjabcdefin/skincare-resume-app
servers:
  web:
    - sjabcdefin.com
proxy:
  ssl: true
  host: sjabcdefin.com
registry:
  username: sjabcdefin
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
env:
  secret:
    - RAILS_MASTER_KEY
ssh:
  user: tomoka
  port: 1201
