service: skincare-resume-app
image: sjabcdefin/skincare-resume-app
servers:
  web:
    - sjabcdefin.com
proxy:
  ssl: true
  host: sjabcdefin.com
  app_port: 3000
registry:
  username: sjabcdefin
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
  args:
    KAMAL_BUILD: "true"
env:
  clear:
    POSTGRES_USER: appuser
    POSTGRES_HOST: 133.167.73.173
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
ssh:
  user: tomoka
  port: 1201
